name: Build & Test

on: [push, pull_request]
  
jobs:
  build:

    runs-on: windows-latest
  
    defaults:
      run:
        working-directory: ./src
        
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    
    - name: Restore Packages
      run: dotnet restore LicenseClearingTool.sln 
      
    - name: Build
      run: msbuild -m -t:Rebuild -p:Configuration=Release -bl:continous-clearing.binlog -noconlog LicenseClearingTool.sln
    
    - name: Archive Build Log
      uses: actions/upload-artifact@v2
      if: ${{ success() || failure() }}
      with:
        name: Compile_Solution_log
        path: |
          src/*.binlog
          
    - name: Create zip
      id: packageBuildResults
      run: |
        $sourceFolder = Join-Path $env:GITHUB_WORKSPACE "out" | Join-Path -ChildPath "*"
        $outFolder = Join-Path $env:GITHUB_WORKSPACE "out" | Join-Path -ChildPath "LicenseClearingTool" 
        New-Item -ItemType Directory -Force -Path $outFolder
        $fileName = "LicenseClearingTool.zip"
        Write-Host "Filename: '$fileName'"
        Write-Host "sourceFolder: '$sourceFolder'"
        Write-Host "Outfolder: '$outFolder'"
        dir
        $outPath = Join-Path $outFolder $fileName
        Compress-Archive -DestinationPath $outPath -Path $sourceFolder -CompressionLevel Optimal
      
    - name: Archive Build Result
      uses: actions/upload-artifact@v2
      with:
        name: LicenseClearingTool
        path: |
           out/LicenseClearingTool
           
  #  - name: Test
   #   run: |
    #    $TestProjects = Get-ChildItem -Path *.UTest.csproj -Recurse
    #    foreach ($Project in $TestProjects) 
     #   {                 
      #          Write-Host $Project.DirectoryName
       #         $TestProject = $Project.DirectoryName
        #        Push-Location $Project.PSParentPath
         #       dotnet test --no-build --configuration Release
     #   }
      
    - name: Create Nuget Packages
      run: |
        $packageOutFolder = Join-Path $env:GITHUB_WORKSPACE "out" | Join-Path -ChildPath "NuGet"
        dotnet pack LicenseClearingTool.sln --no-build --configuration Release --output $packageOutFolder
         
        Write-Host "Save filenames of created NuGet packages..."
        $packages = gci -Path $packageOutFolder -File -Filter "*.nupkg" | select -ExpandProperty Name
          
                
    - name: Archive NuGet Packages
      uses: actions/upload-artifact@v2
      with:
        name: nuget-LicenseClearingTool
        path: |
          out/NuGet
