name: Build & Test

on: [push, pull_request]
  
jobs:
  build:

    runs-on: windows-latest
  
    defaults:
      run:
        working-directory: ./src
        
        
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - uses: actions/cache@v2
      id: cache
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    
    - name: Restore Packages
      run: dotnet restore LicenseClearingTool.sln 
      
    - name: Build
      run: msbuild -m -t:Rebuild -p:Configuration=Release -bl:continous-clearing.binlog -noconlog LicenseClearingTool.sln
    
    - name: Archive Build Log
      uses: actions/upload-artifact@v2
      if: ${{ success() || failure() }}
      with:
        name: log-win-x64-release
        path: |
          src/*.binlog
