name: Publish Pacakges

on:
  workflow_dispatch: { }
  release:
    types: [published]
  
  
jobs:
  publish:
    runs-on: windows-latest
    
    steps:
      - name: Download NuGet Packages from Release
        run: |
            Write-Host "GITHUB_REF: '$($env:GITHUB_REF)'"
            $prefix = "refs/tags/"
            $name = $($env:GITHUB_REF).Substring($prefix.Length)
            Write-Host "name: '$name'"
            gh release download $name --repo siemens/continuous-clearing --pattern '*.nupkg'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Publish to NuGet.org
        run: |
          dotnet nuget add source --username ${{ secrets.USERNAME }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/siemens/index.json" 
          dotnet nuget push "*.nupkg" --api-key $($env:PAT_GITHUB) --source "github"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
